### ISSUE TITLE
Interpolate build_file placeholders with the values from Github contexts

### ISSUE THREAD

**Issue by alambike** [prefapp/action-flavour-images-matrix-generator#12]
### Motivation

We want to allow in this action to interpolate placeholders that follow the Github context variable syntax, provided in the build_file, when loaded.

Example:
```yaml
default:
  triggers:  
    push:  
      branches: ["master"] 
    prerelease:
    release: 
  build_args:
    TENANT: ${{env.TENANT}}
```

The [Build class](https://github.com/prefapp/action-flavour-images-matrix-generator/blob/main/utils/Build.js#L30) should be able to interpolate the Github syntax, substituting placeholders with the values extracted from the [Github contexts](https://docs.github.com/en/actions/learn-github-actions/contexts).

### Acceptance criteria
-  [ ] At least it should be able to parse references to ~~`${{secret.*}}`~~ and `${{env.*}}` contexts

**IMPORTANT**
`${{secrets.*}}` can not be interpolated, as actions has no direct access to repository or organization secrets. See https://github.community/t/accessing-secrets-of-custom-actions-repo/126280
https://docs.github.com/en/actions/security-guides/encrypted-secrets#accessing-your-secrets
