### ISSUE TITLE
New distribute.yml file

### ISSUE THREAD

**Issue by frmadem** [prefapp/action-flavour-images-matrix-generator#18]
# Motivation

The new CI system prefapp is working on, needs to produce to types of distributables:

* artifacts: pieces of software prepared to be consumed by other programs/applications in the form of libraries, modules...
* images: docker images that encapsulate an applications or services with its dependencies. 

Therefore, the current build-images.yaml can not cover all the cases: enter the distribute.yml file!!!

## About the distribute.yaml file

This file is, basically divided in two main sections:

1. **images**: with the declarations about which images to build and how to build them. 
2. **artifacts**: with the declarations about the libraries/modules that should be produced and when to produce them. 

```yaml
# A distribution file example
images:
  default: # this is the flavour
    triggers: # when 
      push_main:
    dockerfile: Dockerfile
    build_args: 
      BASE_URL: https://demo.bs.prefapp.es
    registries: # to push the image to
      - a
      - b
artifacts:     
  npm:
    triggers: 
      push_main: 
    npmrc:
      - @prefapp:registry=https://npm.pkg.github.com # an example 
  maven:

```
