### ISSUE TITLE
Release based on tag

### ISSUE THREAD

**Issue by frmadem** [prefapp/action-flavour-images-matrix-generator#30]
# Motivation

In a monorepo the build-images file should let us express different builds according to a release/prereelease tag. 

The problem is that nowadays the system only controls the event. Therefore:

```yaml
backend:
  triggers:  
    release: 
  dockerfile: Dockerfile.backend
frontend:
  triggers:  
    release: 
  dockerfile: Dockerfile.frontend
```

this file means that both flavours (front and back) are going to be built when a release is performed. 

In a monorepo context, it is common to just release a new version of one flavour (i.e backend of frontend) not being necessary to build everything that is not affected. 

## Posible solution

The solution proposed here is to be able to filter by tags. 

Whenever the release is performed the action can search for the tag linked to the release and filter by it. 

Therefore, our build-images file could have the following syntax:

```yaml
backend:
  triggers:  
    release: 
      release_tag: "^backend-v.*"
  dockerfile: Dockerfile.backend
frontend:
  triggers:  
    release:
      release_tag: "^frontend-v.*" 
  dockerfile: Dockerfile.frontend
```
