### ISSUE TITLE
Support extra tags per flavor

### ISSUE THREAD

**Issue by tonirvega** [prefapp/action-flavour-images-matrix-generator#32]
# Motivation

As a user of the action, I would appreciate the ability to append additional tags to the docker image.

```yaml
# build-images.yml
foz-flavour:
  triggers:  
    push:  
      branches: ["main"] 
    prerelease:
    release:
  extra_tags:
    - latest
  build_args:
    TENANT: "foz"
    SHA: "${{env.GITHUB_SHA}}"
```

then on my ci

```yaml
      - name: Build and push full
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ${{ matrix.dockerfile }}
          build-args: |
            ${{ matrix.build_args }}
          tags: |
            ${{ matrix.tags }}  <--- It contains the autogenerated tag + extra tags
```

# Use case

In this workflow I have to make this extra logic to make it works for the moment.

https://github.com/prefapp/gitops-k8s/blob/d82ccc03d977cd459082e350c6ff5e31d278d0aa/.github/workflows/build_and_dispatch.yaml#L60-L84
